### ISSUE TITLE
When pop ac-menu, Can I auto enable ac-isearch ?

### ISSUE THREAD

**Issue by zw963** [auto-complete/auto-complete#188]
I want to ask some question, Thanks.

When pop ac-menu, Can I auto enable ac-isearch ?

e.g. When in message-mode, when all mail-address popup,  I want auto-isearch it. (don't press C-s)

I still have another problem, 

Can I active ac-menu When I press TAB,  even there is no content in point? 
That is to say:  offer a key(or binding), when press this key, can active the ac-menu.
 I have tried (ac-set-trigger-key "TAB"), But it do nothing. 

BTW: I find a little problem:

if I set  (setq ac-auto-show-menu nil), when I use M-n active ac-menu, ac-search and other ac-menu-map hotkey can not use.

**Comment by futurist** [comment]
I'm using below code to work around this:

````lisp
(defun ac-trigger-isearch ()
  "Trigger ac isearch using -"
  (interactive)
  (if (ac-menu-live-p)
      (ac-isearch)
    (insert "-")
    ))

(global-set-key (kbd "-") 'ac-trigger-isearch)
````

So, if this is a popup for ac, `-` will trigger `ac-isearch`

**Comment by zw963** [comment]
Thanks @futurist , Although, this hack annoy me a little when a unexpectation ac-isearch

**Comment by zw963** [comment]
Oh, My god, I found I reissue almost same issue three times, please see #478

**Comment by zw963** [comment]
Thanks @m2ym, is you consider add a function like #478 ?
