### ISSUE TITLE
Should ac-start be invoked automatically if we are not (looking-back (rx alnum)) ? 

### ISSUE THREAD

**Issue by yangyingchao** [auto-complete/auto-complete#191]
Sorry for the misunderstanding title. I'll explain it here. I'm a c++ programmer. And in a
source file, if too many header files are included, and then if I typed 

std::

then ac will will cause Emacs lose response.

I don't know the exactly reason, but it seems that ac is trying to start complete it using
ac-source-semantic, which  because it will try to analyze all included files and try to use
the result as candidates. As the prefix is a standard namespace, there would be too many
candidates. So I wonder if we ac-start should be invoked through ac-handle-post-command if
cursor is not at the end of a word.

following is my configuration of ac:

``` lisp
(defun my-ac-config ()
  (ac-flyspell-workaround)
  (setq ac-auto-start 3)
  (setq ac-dwim t)
  (setq ac-quick-help-delay 0.5)
  (setq ac-override-local-map nil)  ;don't override local map
  (setq ac-ignore-case t)
  (global-auto-complete-mode t))

(mapc
 (lambda(mode)
   (add-to-list 'ac-modes mode))
 '(asm-mode conf-mode html-mode
            emms-tag-editor-mode haskell-mode latex-mode lisp-mode
            literate-haskell-mode org-mode text-mode eshell-mode
            graphviz-dot-mode powershell-mode nxml-mode
            sawfish-mode flyspell-mode objc-mode antlr-mode protobuf-mode))

(my-ac-config)
```

Thank you.

**Comment by dickmao** [comment]
We are a bit skeptical of cedet semantic's current operability.  We have even less confidence in ac-source-semantic.
