### ISSUE TITLE
1.4 release

### ISSUE THREAD

**Issue by tkf** [auto-complete/auto-complete#219]
Why not just release 1.4 as-is?  Frankly speaking, I don't want to put too much effort for the current code base since I know @m2ym is going to do a major refactoring for 2.0.  For example, I don't want to write docstring for functions that are going to disappear.

I categorize the issues that are in 1.4 milestone.  To me, they are either not-urgent bug or problem that requires a major refactoring.
### Need refactoring / discussion:
- # 148: it seems that auto-complete doesn't support the behavior like `popup-menu*`
  
  I wrote a patch for this #185 but that patch has a performance problem.  Also isearch won't work.  I think the popup value property has a conceptual issue.  So, I suggest to not do this for 1.4.
- # 83: Abort autocomplete when less than ac-auto-start characters
  
  As I said in the thread, I suggest not to do this in 1.4.
### Not urgent

I don't think these are urgent.  We can do that later.
- # 167 / #149: Documentation
- # 133: semantic: Use yasnippet to complete a function with argument placeholders
- # 199: popup lines get wrapped in terminal mode with linum.el
  
  Isn't it popup.el's problem?
### Trivial task:
- #160: Add version number variable

**Comment by tarsius** [comment]
1.4 has been released a long time ago.
