### ISSUE TITLE
The architecture of 2.0

### ISSUE THREAD

**Issue by m2ym** [auto-complete/auto-complete#225]
I want to discuss here about the architecture of AC 2.0. The main advance of 2.0 is to abolish the property-list style source definition. Instead, I want to adopt the defun style source definition like compay-mode.

Plus, I want to make source definitions more flexible and extensible with good maintainability. The problem is that I don't have much experience about source development. So it is hard for me to decide how flexible an extensible it should be.

Any suggestions are welcome.

**Comment by tarsius** [comment]
This package doesn't even have a maintainer right now.
It is unlikely that it will ever reach 2.0.
