### ISSUE TITLE
Asynchronous sources

### ISSUE THREAD

**Issue by miguel-guedes** [auto-complete/auto-complete#232]
Here's something else I forgot to mention. Does auto-complete support asynchronous sources?

I'm developing a component that I would very much like to integrate with auto-complete but so far all my best efforts have failed due to the retrieval of data (the candidates) relying on an async network process (via make-network-process/send-process-string). This means that my component can't provide auto-complete with the candidates when it requests them.

Is there a way to feed candidates to auto-complete on demand?

**Comment by dickmao** [comment]
Yes, do check out company-mode.

**Comment by miguel-guedes** [comment]
Closing stale issue.
