### ISSUE TITLE
auto-complete `ac-update-greedy` error

### ISSUE THREAD

**Issue by stardiviner** [auto-complete/auto-complete#309]
<nav id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#sec-1">1. <span class="todo Urgent">Urgent</span> auto-complete <code>ac-update-greedy</code> error <code>[/]</code></a></li>
</ul>
</div>
</nav>

### Urgent auto-complete `ac-update-greedy` error <code>[/]</code>

-   State "Urgent"     from ""           <span class="timestamp-wrapper"><span class="timestamp">[2014-04-09 Wed 14:07]</span></span>

    Error running timer `ac-update-greedy': (wrong-type-argument wholenump -118)

When I'm in this code:

```lisp
    (defun my-insert-keybinding-code ()
      "Insert keybinding code in Org with a keybinding quickly."
      (interactive)
      (insert "=[]= ")
      (back|)
      )
```

**Comment by syohex** [comment]
Please reopen if you still have this issue.
