### ISSUE TITLE
auto-complete not support  protobuf-mode ? 

### ISSUE THREAD

**Issue by duzhuoyizui** [auto-complete/auto-complete#373]
My configure : 

    (add-to-list 'load-path "~/.emacs.d/lisp/auto-complete")
    (require 'auto-complete)
    (require 'auto-complete-config)
    (add-to-list 'ac-dictionary-directories
                 "~/.emacs.d/auto-complete/dict")
    (ac-config-default)
    (setq ac-use-quick-help nil)
    (setq ac-use-menu-map t)
    (define-key ac-menu-map "\C-n" 'ac-next)
    (define-key ac-menu-map "\C-p" 'ac-previous)
    (global-set-key "\M-/" 'auto-complete)
    (global-auto-complete-mode t)

something wrong ? or auto-complete not support protobuf-mode ?

**Comment by syohex** [comment]
Please retry after adding `protobuf-mode` to `ac-modes` as below.

```lisp
(add-to-list 'ac-modes 'protobuf-mode)
```

**Comment by duzhuoyizui** [comment]
Running well...

 thanks  syohex.
