### ISSUE TITLE
Recent auto-complete breaks Yasnippet expansion

### ISSUE THREAD

**Issue by YorkZ** [auto-complete/auto-complete#379]
The following is my snippet:

    # -*- mode: snippet -*-
    # name: forr
    # key: forr
    # --
    for (${1:i = 0}; ${2:i < N}; ${3:i++}) { $0 }

In a C++ buffer, when typing "forr", it expands to the following:

    for (|)i = 0; i < N; i++) {

    }

`|' is the position of the point after expanding the snippet. Hitting TAB wouldn't goto the next field.

The problem won't show up if I either turn off `auto-complete`, or turn off `smartparen`. Therefore, this might not be a problem of auto-complete. If that's the case, my apology.

This problem is really painful, and I would appreciate any help.

Thanks

**Comment by m2ym** [comment]
I can't reproduce this prolem. What versions of `auto-complete` and `yasnippet` are you using? What happens when you only disable `smartparen`?

**Comment by YorkZ** [comment]
Hi Tomohiro,

Thanks for replying. Here's what I did:

1. By default, I have both `auto-complete-mode` and `smartparens-mode` turned on, the problem shows up.
2. I turned off only the `auto-complete-mode` using `M-x auto-complete-mode`, the problem went away.
3. I then did `M-x auto-complete-mode` to turn on `auto-complete-mode`, the problem came back.
4. I did `M-x smartparens-mode` to turn off `smartparens-mode`, the problem went away.
5. I did `M-x smartparens-mode` to turn on `smartparens-mode` again, the problem came back.

I'm using the latest `auto-complete`, git commit "841ca50"; my Yasnippet is also the latest, git commit "197ef7f".


Hope this helps.

Thanks

**Comment by m2ym** [comment]
Great. This helps a lot. I'll look into thisp roblem.

**Comment by YorkZ** [comment]
Thank you very much.

**Comment by stardiviner** [comment]
I experienced this issue too.

**Comment by m2ym** [comment]
I don't find why this happens, but the advice for AC defined in `smartparens.el` seems to be simply wrong.  I can read from this code that the issue isn't the "issue".

```
(defadvice ac-complete (after sp-auto-complete-advice activate)
  "If `smartparens-mode' is active, we check if the completed string
has a pair definition.  If so, we insert the closing pair."
  (when (and smartparens-mode ad-return-value) ; `ac-complete' returns nil if there are no completion candidates.
    (sp-insert-pair))
  ad-return-value)
```

**Comment by m2ym** [comment]
Evaluating `(sp-insert-pair)` at the position after an open paren in `for (a) {}` turns to be `for ()a) {}`. So this seems to be an smartpanen's issue.

**Comment by YorkZ** [comment]
Hi Tomohiro,

Thank you very much for the help. I can confirm you statement below:

> Evaluating (sp-insert-pair) at the position after an open paren in for (a) {} turns to be for ()a) {}

This is so even when `auto-complete-mode` is off.

Also, as soon as I removed the `ac-complete advice` in `smartparens.el`, my original problem went away, and the snippet expands correctly like a charm. So, do you think this advice is totally unnecessary?

I apologize for having suggested the possibility in `auto-complete`, and I REALLY APPRECIATE your help.

Have a nice weekend,

York
