### ISSUE TITLE
Possible to auto-complete without a prefix?

### ISSUE THREAD

**Issue by danrharms** [auto-complete/auto-complete#380]
Sometimes I would like to use the very nice auto-complete framework to select from a set of candidates, but without first typing a prefix.  Perhaps I do not know the candidate set before-hand, and cannot reliably guess a valid first character.  Or perhaps the candidate set simply does not require a prefix.  But I didn't see a way to do this in auto-complete.  Did I miss it?

**Comment by syohex** [comment]
It is possible if the auto-complete source supports `prefix` parameter and
its `requires` paramter is 0. For example, go-autocomplete.

![auto-complete](https://cloud.githubusercontent.com/assets/554281/5992301/d4ada52c-aa66-11e4-8260-f50895476b62.png)

If cursor is just after `.`, it is possible to complete without prefix.

**Comment by danrharms** [comment]
And ac-auto-start needs to be non-nil, I suppose.
Thanks.
