### ISSUE TITLE
ac-quick-help ac-source-semantic issue

### ISSUE THREAD

**Issue by fallchildren** [auto-complete/auto-complete#386]
If the quick help is displayed in cc-mode I get an error message and no quick-help popup.

For example for std::cout:
"Error running timer `ac-quick-help': (wrong-type-argument listp #("cout" 0 1 (symbol "m" document ac-semantic-doc)))" 

I tried to debug the whole process but I'm pretty new to emacs and haven't found the cause of this. Strange thing is that if e.g. "cout" is called directly via 'ac-complete-semantic' the quick-help appears with no error.

my ac-sources value in cc-mode:
(ac-source-c-headers ac-source-yasnippet ac-source-gtags ac-source-semantic ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers)

**Comment by syohex** [comment]
Hmm, I can't reproduce this issue. It looks work well.

![ac-semantic](https://cloud.githubusercontent.com/assets/554281/5992324/0369b6b6-aa68-11e4-996b-c170d2fd69de.png)

Would you tell me how to reproduce this issue ?

**Comment by fallchildren** [comment]
I'm a bit baffled, but I think I found a way to reproduce it:

- I created a header file for my test.cpp with a simple struct "myStruct" in it
- open test.cpp and include header file -> quick help works for "myStruct" 
"#include "test.h"

int main() {
        myStruct tt;
}"

- save file
- restart emacs and open test.cpp again and try to ac myStruct again -> bug occurs

So if semanticdb hasn't created the cache file everything works fine... so it seems for me.
Also I couldn't recreate the cout issue this happens only for some of my existing files which also have semanticdb cache files ...

I hope this helps

**Comment by m2ym** [comment]
Do you see any error message in minibuffer?

**Comment by fallchildren** [comment]
"Error running timer `ac-quick-help': (wrong-type-argument listp #("cout" 0 1 (symbol "m" document ac-semantic-doc)))" this is the error message in the minibuffer.

I found out that ac-source-semantic-raw also suffers from this bug, for me at least

**Comment by syohex** [comment]
I can reproduce Emacs 24.4 and development version
while I cannot reproduce on Emacs 24.3.

I applied following patch and check `before-value` and `after-value` when this error occurs.
```diff
diff --git a/auto-complete.el b/auto-complete.el
index e7301b1..adda3a6 100644
--- a/auto-complete.el
+++ b/auto-complete.el
@@ -1056,6 +1056,9 @@ You can not use it in source definition like (prefix . `NAME')."
     (if (and (integerp ac-limit) (> ac-limit 1) (> (length candidates) ac-limit))
         (setcdr (nthcdr (1- ac-limit) candidates) nil))
     ;; Put candidate properties
+    (cl-loop for candidate in candidates
+             when (string= candidate "copy")
+             return (setq before-value (list :candidate candidate :document document)))
     (setq candidates (mapcar (lambda (candidate)
                                (popup-item-propertize candidate
                                                       'action action
@@ -1064,6 +1067,9 @@ You can not use it in source definition like (prefix . `NAME')."
                                                       'popup-face face
                                                       'selection-face selection-face))
                              candidates))
+    (cl-loop for candidate in candidates
+             when (string= candidate "copy")
+             return (setq after-value (list :candidate candidate :document document)))
     candidates))
 
 (defun ac-delete-duplicated-candidates (candidates)
```

I got following strange result(At this time, `source` argument is `ac-source-words-in-same-mode-buffers`).

`document` is `nil` but document property of `after-value` is
`ac-semantic-doc`(Value of `document` still is `nil`). 

```
ELISP> before-value
(:candidate "copy" :document nil)

ELISP> after-value
(:candidate
 #("copy" 0 1
   (symbol "m" document ac-semantic-doc))
 :document nil)
```

`ac-semantic-doc` expects argument is list, but following case, `ac-semantic-doc` takes
string argument and error occurs.

Why did I get such result ? (Emacs bug ??)

**Comment by m2ym** [comment]
I have some in mind. Maybe sharing `document` propery causes this problem happen.

**Comment by m2ym** [comment]
Fixed.
