### ISSUE TITLE
Emacs - go-autocomplete - "dot" manual complete bug

### ISSUE THREAD

**Issue by mikefaille** [auto-complete/auto-complete#387]
I don't know where is this auto-complete bug with go-lang. 

I think, the best to follow this bug is there :
https://github.com/nsf/gocode/issues/271

Mainly, I just want a cross-reference.
Maybe, this bug come from auto-complete core module.

Thank you for your help.

**Comment by syohex** [comment]
This is `auto-complete` bug.

**Comment by mikefaille** [comment]
@syohex Thank you for your follow up.
I tried you patch 
```bash
wget https://raw.githubusercontent.com/auto-complete/auto-complete/8d95cc17b05885bc04c7acee1a50ca27366c3f4b/auto-complete.el -O
```
I recompiled all my emacs files but I have the same result :-/ .
http://youtu.be/ykoCeNxw9wg

**Comment by m2ym** [comment]
Could you please try again after upgrading via melpa?

**Comment by mikefaille** [comment]
After an upgrade directly from melpa, it works ! Thank you !!!!!!!!
