### ISSUE TITLE
Auto-complete popup broken

### ISSUE THREAD

**Issue by tantric** [auto-complete/auto-complete#394]
The auto-complete popup has not worked for me. I am running Emacs version 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.10) of 2015-03-10. I am using a Debian OS.

I see the error
```
auto-complete error: (wrong-type-argument arrayp t)
```

This first backtrace is when using auto-complet with org mode:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp t)
  popup-live-p(t)
  popup-delete(t)
  ac-remove-quick-help()
  ac-cleanup()
  auto-complete-1(:triggered trigger-key)
  ac-pcmp/self-insert-command-with-ac-start(1)
  call-interactively(ac-pcmp/self-insert-command-with-ac-start nil nil)
  command-execute(ac-pcmp/self-insert-command-with-ac-start)```
```

and this next one is when using a python buffer:
```
Debugger entered--Lisp error: (error "Completion needs an inferior Python process running")
  signal(error ("Completion needs an inferior Python process running"))
  error("Completion needs an inferior Python process running")
  python-completion-complete-at-point()
  completion--capf-wrapper(python-completion-complete-at-point all)
  run-hook-wrapped(completion--capf-wrapper python-completion-complete-at-point all)
  completion-at-point()
  call-interactively(completion-at-point nil nil)
  command-execute(completion-at-point)
```

I re-installed everything and that did not resolve the problem. Am I doing something wrong?

**Comment by syohex** [comment]
Would you tell us how to reproduce this issue ?
- Reproduce code 
- Minimum configuration for reproducing this issue

**Comment by tantric** [comment]
Could it be related to fuzzy. I am tweaking my config it to see what works.
Here is the configuration that caused the issue:
```
(require 'fuzzy)
(require 'auto-complete)
(require 'org-ac)
(setq ac-auto-show-menu t
      ac-quick-help t
      ac-quick-help-delay 0.5
      ac-use-fuzzy t)
(global-auto-complete-mode +1)

;; Org mode auto-complete
(org-ac/config-default)
```

Here is a config that works for python (deleted the above and replaced with below):
```
(require 'auto-complete-config)
(ac-config-default)
```

My main issue is to try to get this work for org mode. Any help would be appreciated.

**Comment by tantric** [comment]
And I should say thank you for an amazingly fast response time. You rock!

**Comment by tantric** [comment]
Narrowed it down to this config snippet:
```
(setq ac-auto-show-menu t
      ac-quick-help t
      ac-quick-help-delay 0.5)
```

**Comment by syohex** [comment]
Please don't set `ac-quick-help`. This error is occurred by setting this variable.
Type of this variable is not boolean. Users should not use this variable.

**Comment by tantric** [comment]
That fixed it. Thank you so much. I really appreciate the help and quick responses.
