### ISSUE TITLE
After installation presented with the error message

### ISSUE THREAD

**Issue by mattshirtliffe** [auto-complete/auto-complete#396]
Followed installation  http://auto-complete.org/doc/manual.html#installation

Warning (initialization): An error occurred while loading `/home/matthew/.emacs':

File error: Cannot open load file, cl-lib

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by syohex** [comment]
Sorry its information is old.

Please install cl-lib from [here](http://elpa.gnu.org/packages/cl-lib.html) and put it into load-path.
cl-lib is installed as default from Emacs 24.3 and I recommend you to use Emacs 24.3 or higher.

**Comment by mattshirtliffe** [comment]
Thank you, I really appreciate your assistance.

**Comment by syohex** [comment]
You are welcome.

**Comment by victordmontero** [comment]
Hi, i have a similar error except for the error messages, i followed the installation process described in the README but auto-complete won't work. I also restarted emacs and activated the mode through M-x auto-complete-mode command.
Any help would be appreciate, Thanks
