### ISSUE TITLE
Relative filepath

### ISSUE THREAD

**Issue by bounceme** [auto-complete/auto-complete#397]
Is there a source besides files-in-current-dir that can autocomplete file paths relative to the current file?Files-in-current-dir is fine but I would like to be able to go up directories with a "../".

**Comment by syohex** [comment]
`ac-source-filename` also work for relative path as below.

![auto-complete](https://cloud.githubusercontent.com/assets/554281/6762397/bef676f8-cfa2-11e4-85da-5922054a9dd6.png)

**Comment by bounceme** [comment]
Thank you!
