### ISSUE TITLE
auto-complete error: (void variable ac-source-yasnippet)

### ISSUE THREAD

**Issue by gwbrown** [auto-complete/auto-complete#399]
I'm using Emacs 24.4.1 with Yasnippet 20150323.311 from MELPA with Auto-Complete 20150322.813, also from MELPA.

I get the error in the title whenever I have ac-source-yasnippet enabled.  Anyone know of a fix for this or anything I can do to further diagnose the issue?

**Comment by syohex** [comment]
Do you load `auto-complete-config` ?
If not, please load it.

```lisp
(require 'auto-complete-config)
```

You can use `(ac-config-default)` instead of it.

**Comment by gwbrown** [comment]
That did indeed fix it, I should have RTFM.  My apologies.
