### ISSUE TITLE
Outdated documentation and youtube video

### ISSUE THREAD

**Issue by akozin** [auto-complete/auto-complete#400]
Hello!
Thanks for this very good Emacs extension.
Today i installed this extension and found out, that script popup.el, that required for auto-complete plugin is located in another git repository. 
There is no mention about this in documentation. 
Also I could not found tar archive, that you downloaded in YouTube video.
Thanks.

**Comment by syohex** [comment]
Sorry we did not update document.

Please use `package.el` or [el-get](https://github.com/dimitri/el-get/) or [Cask](https://github.com/cask/cask/) for installing `auto-complete` and its dependencies.

I have updated [installation section](https://github.com/auto-complete/auto-complete#install)

**Comment by akozin** [comment]
Thanks for instruction!
