### ISSUE TITLE
Broken the menu display (emacs 24.5 only)

### ISSUE THREAD

**Issue by yaruopooner** [auto-complete/auto-complete#402]
## Broken the menu display (emacs 24.5 only)
The menu display breaks when  'auto-complete' is executed in Emacs 24.5.1.
I called `ac-linum-workaround`, but the effect wasn't obtained.

Emacs 24.5.1でauto-completeを行うとメニュー表示が壊れます
メニューが表示される場所に文字列が存在するとおかしくなるようです。
24.4までは正常表示されていました。
最初linum-modeが有効だからなのかと思い、(ac-linum-workaround)を使用しましたが効果がありませんでした。

## environment
OS:Windows7/Ubuntu14.10
Emacs: 24.4.1/24.5.1

I tested both version.

両方をテストしました。

### 24.4 ( proper )

![win-24 4 1-1](https://cloud.githubusercontent.com/assets/1489073/7214651/33c560e4-e5f0-11e4-8bec-d3e4fc622b52.jpg)

### 24.5 ( broke )

![win-24 5 1-1](https://cloud.githubusercontent.com/assets/1489073/7214655/496d72c4-e5f0-11e4-887c-99b10a984a22.jpg)

## simple test case
I tested on simple environment.
24.4 & 24.5 launch by `$ emacs -Q`.
You open popup.el auto-complete.el, and execute `eval-buffer`.
Switch buffer to *scratch*, and evaluate following code.

よりシンプルな状況でテストしました。
24.4/24.5をそれぞれ `$ emacs -Q` で起動します。
popup.el auto-complete.el を開き、それぞれ `eval-buffer`を行います。
*scratch* へ移動して以下を評価します。

```
(let ()
  (ac-linum-workaround)
  (linum-mode)
  (auto-complete-mode))
font-
0
01
012
0123
```
Evaluate `let`, you execute auto-complete at after `font-`.
24.5 only broke.
popup.el have same symptom.

letを評価して、`font-`でauto-completeを実行します。
すると24.5のみ表示が壊れます。
popup.elだけでも同様の状況です。

```
(let ((hoge "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789"))
  (linum-mode)
  (popup-tip hoge))
```

### before eval
![24 4-24 5-q0](https://cloud.githubusercontent.com/assets/1489073/7214682/59967cc6-e5f1-11e4-8af2-96fd8555f681.jpg)

### afeter eval(1st-figure 24.4, 2nd-figure 24.5)
![24 4-24 5-q](https://cloud.githubusercontent.com/assets/1489073/7214681/4fc50942-e5f1-11e4-8c6f-1bd58a6c0d18.jpg)

以上報告でした。

**Comment by syohex** [comment]
ありがとうございます. 問題は確認できました. 原因を調べます.

**Comment by syohex** [comment]
This issue was introduced at `e589765b881e64c26b29509dd99f2dc51ad44153`

https://lists.gnu.org/archive/html/emacs-diffs/2015-02/msg00047.html

**Comment by gopar** [comment]
Having the same issue, except mine looks worse. I only get one line of completion, the rest disappear. I can still see scroll bar. That's about it

![bug](https://cloud.githubusercontent.com/assets/1545083/7625024/c48980f0-f9a6-11e4-8fa2-440da6dcc727.png)

**Comment by Distopico** [comment]
Same error.. emacs 24.5

![Emacs menu error](http://a.pomf.se/xdyzzx.png)

**Comment by cammsaul** [comment]
I'm seeing the same thing on emacs 24.5 on OS X

**Comment by cammsaul** [comment]
I was able to work around it by installing `pos-tip` and setting`ac-quick-help-prefer-pos-tip` to `t`

**Comment by fallchildren** [comment]
same issue here on emacs 24.5 on ArchLinux - speaking out the obvious:
this is more an issue with popup.el than with auto-complete as flycheck-pos-tip (which uses popup.el) is also affected by this issue

**Comment by fallchildren** [comment]
I tried to debug the process and it seems like the <b>after-string</b> value of some overlays in "popup-set-line-item" function of popup.el (l. 386 - 391) are not rendered at all resulting into some blank lines with only the first char left displayed ( the one which is cut off of the content string before).

**Comment by rustyhu** [comment]
I meet the same issue. I am a newbie to Emacs, so maybe not much information I can provide.
And I find something strange. Here is a test i made with my .emacs file.
When i typed something like a function name to trigger completion, if the pop-up menu located at blank area(no text already there), it looked normal, as following photo shows:
![git_tmp1](https://cloud.githubusercontent.com/assets/3363383/8023591/6bb64ace-0d44-11e5-8edd-2a0861b5ad4b.jpg)

but if the menu appeared at area where texts existed already, the completion would look broken,as this photo:
![git_tmp2](https://cloud.githubusercontent.com/assets/3363383/8023592/819ea66a-0d44-11e5-851d-4cdb2f1af65b.jpg)

At last I want to say, right now when I type these word in *scratch* buffer, even if the pop-up menu overlaped some text, it behaved normal. Really strange.
Emacs version 24.5 on windows 7.

**Comment by AlexChesters** [comment]
+1

**Comment by gopar** [comment]
@AlexChesters I just moved to Company-mode.

**Comment by syohex** [comment]
I wrote patch https://github.com/auto-complete/popup-el/pull/93.

**Comment by syohex** [comment]
My patch is merged.
Please upgrade popup and try.

**Comment by fallchildren** [comment]
works :) haven't found any issues yet.

**Comment by syohex** [comment]
Please reopen if you still have this issue.

**Comment by yaruopooner** [comment]
This problem still occurs.
After this patch,
It becomes strange in not only 24.5 but also 24.4.

It will occurs in the following.
-linum-mode enabled.
-something is displayed on the fringe.(e.g.  hideshowvis, flymake marker...)

この問題はまだ残っているようで、
今回のパッチ以後、以前より酷い状態になっているケースも見受けられます。
※私の環境固有の問題なのかはまだ確認できていませんが・・・
パッチ後にlisp-modeなどで確認すると、大抵は動いていますが、
linum-modeやhideshowvisを使うとやはりおかしくなります。
また、C/C++-modeなどではlinum-mode, hideshowvis, flymakeなどを使っていますが、
fringeにhideshowvisの`+ -`や flymakeの`!`が表示されている行のpopup表示が壊れます。
popupの表示幅が小さいときほど壊れる率が高い気がします。
若干症状は異なるものの、この症状は24.4でも発生するようになってしまいました。

**Comment by AlexChesters** [comment]
I downgraded my version of emacs to 24.4 and it fixed it for me, strange.

**Comment by syohex** [comment]
@yaruopooner Please show us screenshots.

I will try to check with linum-mode.

**Comment by yaruopooner** [comment]
### scratch buffer
`buffer start condition`
![_scratch-0](https://cloud.githubusercontent.com/assets/1489073/8408751/a4647a2e-1ead-11e5-990c-3061c07bfda2.png)

`linum : on`
`hideshowvis : on`
![_scratch-broken-all-enable](https://cloud.githubusercontent.com/assets/1489073/8408767/bbc65e44-1ead-11e5-9c2e-c07e49b8f756.png)

`linum : on`
`hideshowvis : off`
![_scratch-hideshow-off](https://cloud.githubusercontent.com/assets/1489073/8408784/e9795af8-1ead-11e5-8732-ddb25d1cb073.png)

`linum : off`
`hideshowvis : on`
![_scratch-linum-off](https://cloud.githubusercontent.com/assets/1489073/8408791/eec20802-1ead-11e5-8708-8c3302650a7d.png)

`linum : off`
`hideshowvis : off`
![_scratch-broken-all-disable](https://cloud.githubusercontent.com/assets/1489073/8408793/f8cbc8ce-1ead-11e5-97e6-9dc054478a00.png)

`normal completion(buffer after erase)`
![_scratch-normal-completion](https://cloud.githubusercontent.com/assets/1489073/8408799/030565ac-1eae-11e5-91f1-0181396b651b.png)

**Comment by yaruopooner** [comment]
### C++-mode 1
`buffer start condition`
![_c -mode-0-all-enable](https://cloud.githubusercontent.com/assets/1489073/8408989/4dd4324c-1eaf-11e5-9451-c1dbc8dae99b.png)

`linum : on`
`hideshowvis : on`
![_c -mode-1-all-enable](https://cloud.githubusercontent.com/assets/1489073/8409001/6d30abde-1eaf-11e5-8483-4831214027ba.png)
![_c -mode-2-all-enable](https://cloud.githubusercontent.com/assets/1489073/8409006/7707511c-1eaf-11e5-8a10-1a2a38acb799.png)

`linum : off`
`hideshowvis : on`
![_c -mode-2-linum-off](https://cloud.githubusercontent.com/assets/1489073/8409018/8d469708-1eaf-11e5-8d6b-1501820f09ff.png)


`linum : off`
`hideshowvis : off`
![_c -mode-2-linum hideshow-off](https://cloud.githubusercontent.com/assets/1489073/8409031/9d9026e2-1eaf-11e5-88c3-c7edcf50fd99.png)

### C++-mode 2
`buffer start condition`
![_c -mode-4-linum hideshow-off-0](https://cloud.githubusercontent.com/assets/1489073/8409077/e8c9d96e-1eaf-11e5-8f0a-cf82a413f3d8.png)

`linum : off`
`hideshowvis : off`
`flymake : on`
![_c -mode-4-linum hideshow-off-1](https://cloud.githubusercontent.com/assets/1489073/8409085/f7b5c596-1eaf-11e5-9a98-00a0fba3c8c0.png)

`linum : off`
`hideshowvis : off`
`flymake : off`
![_c -mode-4-linum hideshow-off-1](https://cloud.githubusercontent.com/assets/1489073/8409100/089f1452-1eb0-11e5-9f19-102302f59bae.png)

**Comment by syohex** [comment]
BTW @yaruopooner I suppose it is better to use `pos-tip` tooltip instead of popup.el if you install plugins which handles fringe or window gutters.

**Comment by yaruopooner** [comment]
@syohex Thank you great advice. 
Problem was solved!
I always use `pos-tip`.

**Comment by river06** [comment]
Same issue here:
http://emacs.stackexchange.com/questions/18426/autocomplete-popup-menu-broken-emacs-24-5-1

**Comment by isolet** [comment]
Any news?

**Comment by syohex** [comment]
Sorry, no news.
