### ISSUE TITLE
C struct member completion can't work

### ISSUE THREAD

**Issue by zijianyue** [auto-complete/auto-complete#409]
In the below example, when I complete after aa.,it shows not only the members of TypeA but also some other symbols begin with 'l'.

``` c
typedef struct tagTypeA
{
    int longitude;
    int latitude;
}TypeA;

void main()
{
    int last = 0;
    tagTypeA aa;
    aa.
}
```

**Comment by syohex** [comment]
Default completion is not so smart. It checks only characters and does not check context, data types etc. You should use libclang based extensions for smart completing. There are some extensions which are based on libclang. Please check following extensions.

- [irony-mode](https://github.com/Sarcasm/irony-mode/)
- [clang-complete-async](https://github.com/Golevka/emacs-clang-complete-async)
- [auto-complete-clang](https://github.com/brianjcj/auto-complete-clang)

**Comment by zijianyue** [comment]
But in the early version , before 2012-12-8, it worked smartly.

**Comment by syohex** [comment]
I'll check that revision.

**Comment by innerout** [comment]
If you integrate auto-complete with semantic you can have what you ask.
