### ISSUE TITLE
Symbol's function definition is void: yas/current-snippet-table 

### ISSUE THREAD

**Issue by g-ortuno** [auto-complete/auto-complete#411]
I just installed auto-complete from MELPA and I keep getting this error for C++ files.

The only two lines in my .emacs are

``` emacs
(require 'auto-complete-config)
(ac-config-default)
```

Everything works if I remove those two lines and just do M-x auto-complete-mode.

**Comment by syohex** [comment]
Would you show us value of `yas--version` ?
(`M-x describe-variable`, yas--version)

If you use old version yasnippt(<= 0.6.0), please upgrade yasnippet and try again.

**Comment by g-ortuno** [comment]
I don't even have yasnippt installed...

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue.
If you don't install yasnippet and load it, you never get this error message.

**Comment by g-ortuno** [comment]
*sigh* is there anything else I can provide to make it easier to find the problem? Otherwise feel free to close the issue.

**Comment by syohex** [comment]
> Is there anything else I can provide to make it easier to find the problem?

Sorry, no way. I try to reproduce this issue some Emacs version but I cannot reproduce yet.

Would you tell us output of `M-x load-library yasnippet` and `M-: (require 'yasnippet)` ?

And please try again after removing and reinstall auto-complete ?

**Comment by g-ortuno** [comment]
Interesting. It seems I do have yasnippet installed. The valu eof yas--version is `0.8.0beta`

**Comment by syohex** [comment]
If you install yasnippet `0.8.0beta`, it defined `yas-active-keys`.

https://github.com/capitaomorte/yasnippet/blob/5aebe46e5c50ac9375ac2271c7a7e4f2df442eb3/yasnippet.el#L2621

and following condition returns true.

https://github.com/auto-complete/auto-complete/blob/8978bd77257a3fe4a166cd335cc217f9fac521ea/auto-complete-config.el#L144

So following code is not evaluated and you don't get this error message(`Symbol's function definition is void: yas/current-snippet-table`)

https://github.com/auto-complete/auto-complete/blob/8978bd77257a3fe4a166cd335cc217f9fac521ea/auto-complete-config.el#L160
