### ISSUE TITLE
no such file or directory "popup"

### ISSUE THREAD

**Issue by vyp** [auto-complete/auto-complete#415]
$ emacs --debug-init

    Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "popup")
      require(popup)
      byte-code("\300\301!\210\300\302!\207" [require cl-lib popup] 2)
      require(auto-complete)
      byte-code("\300\301!\210\300\302!\207" [require cl-lib auto-complete] 2)
      require(auto-complete-config)
      eval-buffer(#<buffer  *load*> nil "/home/rws/.emacs.d/init.el" nil t)  ; Reading at buffer position 1684
      load-with-code-conversion("/home/rws/.emacs.d/init.el" "/home/rws/.emacs.d/init.el" t t)
      load("/home/rws/.emacs.d/init" t t)
      #[0 "\205\262

So I add:

    (add-to-list 'load-path "~/etsi/emacs-packages/auto-complete/.cask/24.5.1/elpa/popup-20150626.711")

to init.el and it works. Question is, I don't think that is correct way to do it (http://auto-complete.org/doc/manual.html#manual-installation does not say it), so how do I make cask load dependencies properly in my init.el?

[init.el](https://github.com/vyp/etsi/blob/e7e0e6bc6b322faa032c10d0f36ee45a94835f73/emacs/.emacs.d/init.el#L36-58) (I already did `make byte-compile`.)

**Comment by syohex** [comment]
You should not use Cask in `auto-complete` directory. It is used only for debug and unit testing.

I recommend you to use package manager such as package.el, el-get, Cask etc. Package manager sets load-path automatically and installs package dependencies. You need not to set load-path manually by them.

For example package.el, You add following configuration to your init.el

```
(require 'package)
;; If you want to use stable version, please use melpa-stable
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
```

You can install package `M-x package-list-packages` or `M-x package-install`.

`package-initialize` function sets load-path of packages which you install.

See also
- http://emacswiki.org/emacs/ELPA
- http://ergoemacs.org/emacs/emacs_package_system.html
- https://github.com/dimitri/el-get

**Comment by vyp** [comment]
But `make byte-compile` requires cask? Even if I compile without makefile, popup still has to be provided?

**Comment by vyp** [comment]
Also the popup is sometimes a bit [buggy](http://i.imgur.com/ZqpfI41.png), is this expected/unavoidable? Main reason I not using package manager because it does seem reproducable i.e. seems to be no way to specify a git hash to build from. Am I wrong?

**Comment by syohex** [comment]
> But make byte-compile requires cask? Even if I compile without makefile, popup still has to be provided?

Yes. However it is also used for testing. Package manager byte-compiles packages when you install.

> Main reason I not using package manager because it does not seem reproducable i.e. seems to be no way to specify a git hash to build from. Am I wrong?

`el-get-lock` provides version lock feature.
- https://github.com/tarao/el-get-lock

**Comment by vyp** [comment]
> el-get-lock provides version lock feature.

Thanks for mentioning it, it works great. :smile:

This is off topic, but would you know why it's not part of el-get itself? As in, if they incorparate it and add tests for it, wouldn't it mean el-get-lock is less likely to break or be incompatible in the future? It seems like a **really** useful feature to have. cc @tarao
