### ISSUE TITLE
When (setq ac-auto-start t), line number goes wrong

### ISSUE THREAD

**Issue by lolosssss** [auto-complete/auto-complete#418]
![screenshot from 2015-09-23 11-55-13](https://cloud.githubusercontent.com/assets/3444544/10037570/ac0dffea-61ea-11e5-9036-b0bb5d053af6.png)

**Comment by syohex** [comment]
Could you add check with adding following configuration to your configuration file ?

```lisp
(ac-linum-workaround)
```

**Comment by lolosssss** [comment]
It works. Thanks
