### ISSUE TITLE
Fail to install auto-complete. It's caused by auto-complete.el and auto-complete-config.el compile error

### ISSUE THREAD

**Issue by elloop** [auto-complete/auto-complete#431]
I fail to install auto-complete neither by list-packages method nor manual install. 

My Emacs version is emacs-24.3-bin-i386.zip,  i use the ("melpa-stable" . "https://stable.melpa.org/packages/") for my package archive. in the list-package page, it says the auto-complete stable version is 1.5.

After i typing 'yes' to confirm to install v1.5 in list-package page, during Emacs compile files, i meet the following errors:

`auto-complete.el:57:1:Error: Symbol's value as variable is void: closed`

and

`auto-complete-config.el:29:1:Error: Cannot open load file: auto-complete`

Then, i study the auto-complete manual, according to [Auto-Complete Manual](http://auto-complete.org/doc/manual.html), 

i follow the manual-install method:

>If you can't use Makefile, open the directory from Emacs by C-x d and type * . el RET B RET to do byte-compile.

when i byte-compile auto-complete.el and auto-complete-config.el, i get the same errors as before.

please help me, how can i successfully install the auto-complete package? thanks.

**Comment by syohex** [comment]
I cannot reproduce this issue.

`auto-complete.el:57` is here, loading popup.el

https://github.com/auto-complete/auto-complete/blob/v1.5.0/auto-complete.el#L57

popup.el 0.5.3 is here

https://github.com/auto-complete/popup-el/blob/v0.5.3/popup.el

There is no **closed** variable. I wonder why you got such error.

Could you retry to install ?

> auto-complete-config.el:29:1:Error: Cannot open load file: auto-complete

I suppose you did not set `load-path` correctly. Please check.

**Comment by elloop** [comment]
@syohex Thank you. But I still fail to install the package.

I've installed popup, and tried to reinstall auto-complete. I've also checked my load-path, they are both in load-path:

"c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/auto-complete-1.4" "c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/popup-0.5.3"

Following is the reinstall process:

I remove the melpa-stable package archive and add  ("marmalade" . "http://marmalade-repo.org/packages/").

I just install the popup package because the auto-complete seems depand on popup. 

Here is the result of `M-x package-install RET popup` :

> Compiling no file at Wed Mar  2 18:49:22 2016
Leaving directory `c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/popup-0.5'

Compiling file c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/popup-0.5/popup-pkg.el at Wed Mar  2 18:49:22 2016
Entering directory `c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/popup-0.5/'

Compiling file c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/popup-0.5/popup.el at Wed Mar  2 18:49:22 2016
popup.el:31:1:Warning: cl package required at runtime
In popup-isearch-update:
popup.el:860:8:Warning: function popup-isearch-update used to take 3-4
    arguments, now takes 2-3

It seems succeed.

Then I type: `M-x package-install RET auto-complete RET` to install auto-complete again.

(this time auto-complete is V1.4 on marmalade-repo.org.)

I get following errors again:


> Compiling file c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/auto-complete-1.4/auto-complete-config.el at Wed Mar  2 18:43:51 2016
Entering directory `c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/auto-complete-1.4/'
auto-complete-config.el:31:1:Error: Symbol's value as variable is void: closed

Compiling file c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/auto-complete-1.4/auto-complete-pkg.el at Wed Mar  2 18:43:52 2016

Compiling file c:/Users/elloop/AppData/Roaming/.emacs.d/elpa/auto-complete-1.4/auto-complete.el at Wed Mar  2 18:43:52 2016
auto-complete.el:49:1:Error: Symbol's value as variable is void: closed


line 31 of auto-complete-config.el is :

`(require 'auto-complete)`

and line 49 of auto-complete.el is :

`(require 'popup')`

My OS: windows 10, 64bit
Emacs: 24.3.1

I'm confused. Help :(

**Comment by elloop** [comment]
Good news. I finally install AC successfully. 

I delete my whole .emacs.d directory, and git clone it again.

Then I type `M-x package-install RET auto-complete` directly, and I succeed.

Maybe it is because that I have too much rubbish in my .emacs.d or init.el. Thank you @syohex .
