### ISSUE TITLE
Faster auto-completion in org-mode

### ISSUE THREAD

**Issue by DJJ88** [auto-complete/auto-complete#435]
Hello,
I'm using auto-complete in org mode but I notice that there is more delay in the completion in org-mode than in text mode for example.

I tried to customize auto-complete by reducing the delay to a maximum but it didn't improve in org-mode.

Do you know what is causing this delay and if it's is possible to improve it?

**Comment by syohex** [comment]
Could you show us in more detail ?
- ac-sources in org-mode ?
- File size, lines, words ?
- profiling, `M-x profiler-start` -> `M-x profiler-report`

**Comment by DJJ88** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> Could you show us in more detail ?
>
> * ac-sources in org-mode ? 
> * File size, lines, words ? 
> * profiling, M-x profiler-start -> M-x profiler-report 
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub


Hello

Thank for suggesting profiling. I think the problem comes from
flyspell-mode. Do you have any idea why it is the case?

* I don't have any specific source in org-mode.
* The file size does not seem to matter in my case.
* I used a file of about 5 mb and typed a paragraph is org-mode and then
* typed the same paragraph in text-mode. Here is the profiling output

** Org-mode

- flyspell-post-command-hook                                     3500  47%
 - byte-code                                                     3491  47%
  + flyspell-check-word-p                                        3081  41%
  + flyspell-word                                                 315   4%
  + flyspell-check-pre-word-p                                       7   0%
- timer-event-handler                                            1190  16%
 + byte-code                                                     1169  15%
 + timer-activate-when-idle                                         7   0%
 + timer-activate                                                   6   0%
 + timer-inc-time                                                   4   0%
- command-execute                                                1095  14%
 + call-interactively                                            1090  14%
- ...                                                             944  12%
   Automatic GC                                                   933  12%
 - ad-Advice-delete-backward-char                                  11   0%
  - let                                                            11   0%
   - if                                                            11   0%
    - setq                                                         11   0%
     - with-no-warnings                                            11   0%
      - funcall                                                    11   0%
       - #<compiled 0x24711b>                                      11   0%
        - delete-char                                              11   0%
         - apply                                                   11   0%
          - ad-Advice-delete-char                                  11   0%
           - let                                                   11   0%
            + if                                                   11   0%
- ac-handle-post-command                                          300   4%
 - byte-code                                                      297   4%
  - ac-start                                                      286   3%
   + ac-cleanup                                                   139   1%
   + ac-prefix                                                     54   0%
   + ac-init                                                       35   0%
   - ac-put-prefix-overlay                                         22   0%
    + org-element--cache-after-change                               8   0%
    + org-element--cache-before-change                              7   0%
    + jit-lock-after-change                                         3   0%
   + ac-set-show-menu-timer                                         8   0%
   + ac-set-timer                                                   6   0%
   + ac-set-quick-help-timer                                        3   0%
  + ac-inline-update                                                1   0%
+ redisplay_internal (C function)                                 155   2%
+ ac-handle-pre-command                                            91   1%
+ winner-save-old-configurations                                   35   0%
+ yas--post-command-handler                                        19   0%
  x-set-selection                                                   8   0%
+ internal-timer-start-idle                                         5   0%
  undefined                                                         3   0%
+ deactivate-mark                                                   1   0%
  tooltip-hide                                                      1   0%




** Text mode

- timer-event-handler                                           12001  90%
 - byte-code                                                    11986  90%
  + apply                                                       11985  90%
 + timer-activate-when-idle                                         5   0%
 + timer-inc-time                                                   2   0%
   cancel-timer-internal                                            1   0%
- ...                                                             729   5%
   Automatic GC                                                   729   5%
- command-execute                                                 218   1%
 - call-interactively                                             218   1%
  - byte-code                                                      93   0%
   - read-extended-command                                         93   0%
    + completing-read                                              89   0%
      funcall                                                       4   0%
  - execute-extended-command                                       44   0%
   + command-execute                                               40   0%
  - ac-expand                                                      36   0%
   - ac-expand-common                                              34   0%
    - ac-complete                                                  33   0%
     - ac-complete-1                                               33   0%
      + ac-cleanup                                                 29   0%
      + ac-expand-string                                            1   0%
  + self-insert-command                                             9   0%
  + ac-complete                                                     3   0%
  + save-buffer                                                     3   0%
- ac-handle-post-command                                          161   1%
 - byte-code                                                      159   1%
  - ac-start                                                      154   1%
   - ac-cleanup                                                    76   0%
      set-cursor-color                                             42   0%
    + ac-menu-delete                                               15   0%
    + ac-remove-quick-help                                         10   0%
    + ac-remove-prefix-overlay                                      5   0%
      ac-comphist-add                                               3   0%
      ac-deactivate-completing-map                                  1   0%
   + ac-prefix                                                     36   0%
   + ac-init                                                       16   0%
   + ac-set-timer                                                   6   0%
     ac-put-prefix-overlay                                          3   0%
   + ac-set-show-menu-timer                                         2   0%
     ac-stop-word-p                                                 1   0%
+ redisplay_internal (C function)                                 125   0%
+ ac-handle-pre-command                                            48   0%
+ winner-save-old-configurations                                   18   0%
+ internal-timer-start-idle                                         3   0%

**Comment by syohex** [comment]
> Do you have any idea why it is the case?

Sorry, no. I suppose you should not always enable flyspell-mode in such case, and enable only at spell checking. flyspell-mode sets own hooks to pre-command-hook, and post-command-hook, after-change-functions. This makes emacs slow.

**Comment by DJJ88** [comment]
Thanks for the information. I'll keep that in mind.

Best regards,




On Wed, Mar 23, 2016 at 5:48 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> Do you have any idea why it is the case?
>
> Sorry, no. I suppose you should not always enable flyspell-mode in such
> case, and enable only at spell checking. flyspell-mode sets own hooks to
> pre-command-hook, and post-command-hook, after-change-functions. This makes
> emacs slow.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/auto-complete/auto-complete/issues/435#issuecomment-200174289>
>



-- 
Jérémie Juste
