### ISSUE TITLE
File error: Cannot open load file, popup

### ISSUE THREAD

**Issue by chujiangke** [auto-complete/auto-complete#438]
guys 
when i after done " make install "step , and add  some text in .emacs below
 " (add-to-list 'load-path "/home/richard/.emacs.d")
(require 'auto-complete-config)
(ac-config-default)
"
then start emacs , and it appear something like this : 
"
Warning (initialization): An error occurred while loading `/home/richard/.emacs':

File error: Cannot open load file, popup

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
" help me please master , i am new emacser.

**Comment by chujiangke** [comment]
i solove it.

git clone https://github.com/auto-complete/popup-el.git

and i get the "popup.el" file . and i move "popup.el" to the path with " -rw-rw-r-- 1 richard richard   117  4月 14 01:07 auto-complete-pkg.el
-rw-rw-r-- 1 richard richard 65163  4月 14 01:07 auto-complete.elc
-rw-rw-r-- 1 richard richard 74632  4月 14 01:07 auto-complete.el
-rw-rw-r-- 1 richard richard 16745  4月 14 01:07 auto-complete-config.elc
-rw-rw-r-- 1 richard richard 19578  4月 14 01:07 auto-complete-config.el
"

and start emacs ok .

**Comment by syohex** [comment]
I recommend you to use package.el(or other package managers like el-get, Cask) for installing auto-complete. You need not to install dependencies manually by them.

See
- https://www.emacswiki.org/emacs/ELPA
- http://ergoemacs.org/emacs/emacs_package_system.html
