### ISSUE TITLE
Prefix Regex

### ISSUE THREAD

**Issue by der-Daniel** [auto-complete/auto-complete#445]
Hi,

so I am trying to build my own `source` file for `auto-complete`.

I was already able to define a prefix for `html tags`.
`(prefix . "<\\(.*\\)")`

Question:
Why can I not use the prefix like this:
`(prefix . "<")`

Is the auto-complete bound to `\1` or something similar?

I am also trying to define a reasonable prefix for `bootstrap` classes.
So far my prefix looks like this 
`(prefix . " class=\"[^\"].*\\(\\)")`

But this does not allow me to use a rule like:  
- must start with `class`
- allow any character expect `"`

What is the problem here?

**Comment by syohex** [comment]
> Question:
> Why can I not use the prefix like this:
> (prefix . "<")
> 
> Is the auto-complete bound to \1 or something similar?

Please see http://auto-complete.org/doc/manual.html#prefix. If regexp is specified, it must has match group.


> I am also trying to define a reasonable prefix for bootstrap classes.
> So far my prefix looks like this
> (prefix . " class=\"[^\"].*\\(\\)")
> 
> But this does not allow me to use a rule like:
> 
>     must start with class
>     allow any character expect "
> 
> What is the problem here?

```lisp
(prefix . "class=\"\\([^\"]*\\)")
```

**Comment by der-Daniel** [comment]
After entering one class, there is no further auto completion for another one.

**Comment by syohex** [comment]
Ah, you can specify a function as prefix. So you can write such parsing function.

**Comment by der-Daniel** [comment]
Yeah that may be more robust.
Can you explain what this "matching to a group" means. Does this mean that the group needs to be empty? Or how is the pointer being calculated from a match?

**Comment by syohex** [comment]
> Can you explain what this "matching to a group" means.

The part surrounded with `\\(` and ``\\) in regular expression.

> Does this mean that the group needs to be empty?

No. Its length is larger than equal zero.

> Or how is the pointer being calculated from a match?

Use `match-beginning`, `match-end` function.
