### ISSUE TITLE
The youtube-video linked in the README is “unavailable”

### ISSUE THREAD

**Issue by ArneBab** [auto-complete/auto-complete#447]
At least that’s the case in Germany. Is there another link?

**Comment by syohex** [comment]
Sorry, no. But you can find some auto-complete video in Youtube.

**Comment by ArneBab** [comment]
Is the video available for you? If not, could you remove it from the README (I think a broken tutorial link gives people the impression that auto-complete isn’t maintained).

**Comment by syohex** [comment]
Thanks for advice. I'll change it later.

**Comment by ArneBab** [comment]
Thank you!

**Comment by syohex** [comment]
Done
