### ISSUE TITLE
Warning when compile & didn't load the path

### ISSUE THREAD

**Issue by frankie8518** [auto-complete/auto-complete#449]
I install the package via melpa.
`M-x package-install`
and I got....(see the fourth paragraph) 

> Leaving directory `/home/shulin8518/.emacs.d/elpa/popup-20160709.729'
> 
> Compiling file /home/shulin8518/.emacs.d/elpa/popup-20160709.729/popup-pkg.el at Sun Jul 10 19:45:20 2016
> Entering directory `/home/shulin8518/.emacs.d/elpa/popup-20160709.729/'
> 
> Compiling file /home/shulin8518/.emacs.d/elpa/popup-20160709.729/popup.el at Sun Jul 10 19:45:20 2016
> 
> Compiling no file at Sun Jul 10 19:45:22 2016
> Leaving directory `/home/shulin8518/.emacs.d/elpa/auto-complete-20160416.604'
> 
> Compiling file /home/shulin8518/.emacs.d/elpa/auto-complete-20160416.604/auto-complete-config.el at Sun Jul 10 19:45:22 2016
> Entering directory `/home/shulin8518/.emacs.d/elpa/auto-complete-20160416.604/'
> 
> Inend of data:
> auto-complete-config.el:544:1:Warning: the following functions are not known to be defined:
>     semantic-analyze-current-context, semantic-tag-class,
>     semantic-tag-function-arguments, yas-expand-snippet,
>     semantic-format-tag-type, semantic-format-tag-name
> 
> Compiling file /home/shulin8518/.emacs.d/elpa/auto-complete-20160416.604/auto-complete.el at Sun Jul 10 19:45:23 2016
> 
> Compiling no file at Sun Jul 10 19:46:12 2016
> 

if i ignore it.
and use `M-x auto-complete-mode`, it just works well.

and i want it open with emacs.
and `(require 'auto-complete)`
use `C-x C-e `to eval it, good.
but when i reopen emacs

> File error: Cannot open load file, no such file or directory, auto-complete

after i fix it with this, it finally open with emacs and works well 
```
;; start auto-complete with emacs
(add-to-list 'load-path  "/home/shulin8518/.emacs.d/elpa/auto-complete-20160416.604/")
(add-to-list 'load-path "/home/shulin8518/.emacs.d/elpa/popup-20160709.729/")
(require 'auto-complete)
;; do default config for auto-complete
(require 'auto-complete-config)
(ac-config-default)
```

**Comment by syohex** [comment]
I'll fix warnings later.

Please call `(package-initialize)` in your conifguration file like `~/.emacs.d/init.el` for setting load-path of packages which are installed by package.el. `load-path` issue is not `auto-complete` issue.

**Comment by syohex** [comment]
NOTE: One warning cannot be fixed. Other warnings can be fixed.
