### ISSUE TITLE
can't install with "package-install" in cygwin

### ISSUE THREAD

**Issue by kerwincsc** [auto-complete/auto-complete#451]
When I try to install "auto-complete" in cygwin,it gives me a hint "NO MATCH".How can I install it in my cygwin?

**Comment by syohex** [comment]
Did you add `melpa` or `melpa-stable` to `package-archives` ?

```lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
```

And `M-x package-refresh-contents` and `M-x package-install auto-complete`.
