### ISSUE TITLE
Org-mode version 8.3.5

### ISSUE THREAD

**Issue by zhzw3889** [auto-complete/auto-complete#454]
I installed org 8.3.5 in elpa and I  met with a problem when I was using it.
When I enter C-c C-e to export for a html-file, after enter "h h", it doesn't output a html-file in my working path, instead, it comes out an information:"Definition not found for footnote 0".
Who can tell me why?And how to slove it?

**Comment by syohex** [comment]
Is it really auto-complete issue ?

**Comment by zhzw3889** [comment]
Sorry, my mistake
