### ISSUE TITLE
Autocomplete doesn't work in Lisp mode

### ISSUE THREAD

**Issue by amirteymuri** [auto-complete/auto-complete#455]
Hi and here is the link to my problem:

http://emacs.stackexchange.com/questions/26221/autocomplete-doesnt-work-in-lisp-mode?noredirect=1#comment39828_26221

**Comment by syohex** [comment]
It looks you resolved this issue by installing ac-slime. Can I close this issue ?

**Comment by amirteymuri** [comment]
Yes, you could close this.
