### ISSUE TITLE
Dead links.

### ISSUE THREAD

**Issue by rubikitch** [auto-complete/auto-complete#462]
http://cx4a.org/software/auto-complete/manual.ja.html
is not found.

http://www.youtube.com/watch?v=rGVVnDxwJYE
is not playable for now.

**Comment by syohex** [comment]
Yes youtube video is dead. And Japanese document is only in old archive(https://github.com/auto-complete/auto-complete/archive/v1.3.1.zip).

**Comment by chadhs** [comment]
the manual is down as well

http://auto-complete.org/doc/manual.html

**Comment by syohex** [comment]
I have removed dead links.

**Comment by chadhs** [comment]
Awesome thank you!  

I see the manual links to the manual in GitHub 👍🏼😎🚀

--  
Chad Stovern // @chadhs
