### ISSUE TITLE
Can I use auto-complete to do completion like in VIM?

### ISSUE THREAD

**Issue by cmal** [auto-complete/auto-complete#463]
For example, I can open a bare vim (without plugin) and input `some_long_object` and then open a new line, and input a `s`, hit `C-x C-p`, it will complete `some_long_object` for me (without hitting an extra selecting key). 
If I input `some_long_object.some_method_really_long` on a new line, then I open a new line and input `s`, then hit `C-x C-p C-x C-p`, it will complete `some_long_object.some_method_really_long` for me. ( do completion sequentially )
Vim can also complete lines like this.
And default Vim completion do things like this: `C-x C-p` will do completion and pop-up a menu, not just pop-up a menu for choosing.
Can`auto-complete` do this?
Thanks!

**Comment by syohex** [comment]
Sorry, No it can't.

**Comment by cmal** [comment]
thanks
