### ISSUE TITLE
Auto completion features doesn't pop up after successfully install and load (M-x)

### ISSUE THREAD

**Issue by fluteguitar** [auto-complete/auto-complete#468]
![emacs-auto-complete-mode](https://cloud.githubusercontent.com/assets/10528635/21576974/9c1118bc-cf7a-11e6-9431-3e96a242dd33.png)

**Comment by syohex** [comment]
Could you show us your configuration ? I think you add following configuration then auto-complete works.

```
(ac-config-default)
```

**Comment by fluteguitar** [comment]
Thank you very much syohex. It works!
