### ISSUE TITLE
[EMACS24] Popup suggestion appears on *scratch* buffer, but does not appear on *.lsp regular buffer

### ISSUE THREAD

**Issue by fluteguitar** [auto-complete/auto-complete#470]
![image](https://cloud.githubusercontent.com/assets/10528635/21747239/b873a7fe-d592-11e6-8380-04ca2eebd6df.png)

**Comment by syohex** [comment]
Do you install [ac-slime](https://github.com/purcell/ac-slime) ? auto-complete does not support Common Lisp completion.

**Comment by fluteguitar** [comment]
Yes, I have already installed.
To not be duplicate, I would like to post the link of the thread I've just opened on ac-slime issue portal.
https://github.com/purcell/ac-slime/issues/12

Thanks you for your support.

**Comment by syohex** [comment]
![slime](https://cloud.githubusercontent.com/assets/554281/21953199/aea2bdf6-da73-11e6-9da9-b043cf5a82c8.png)

It works on my environment.

**Comment by fluteguitar** [comment]
Hello,
I am not sure of whether it is appropriate to reply to a close thread. I just wanna comment that your Emacs theme/interface looks really cool! Hope that I could install the same one on my Emacs.

**Comment by syohex** [comment]
>  I just wanna comment that your Emacs theme/interface looks really cool! Hope that I could install the same one on my Emacs.

This is not 3rd party color theme. Please launch emacs by `emacs --reverse-video`(short options is `-r`).

**Comment by fluteguitar** [comment]
Thank again, syohex.
