### ISSUE TITLE
Filter candidates faces customization

### ISSUE THREAD

**Issue by wandersoncferreira** [auto-complete/auto-complete#473]
Hi,

I would like to know if is possible to customize the faces of the highlight text when I hit C-s to filter candidates inside the popup window.

Example below:
<a href="http://i.imgur.com/qsP0gzJ.png">
  <img src="http://imgur.com/qsP0gzJl.png" />
</a>

It is not possible to see through the highlighting.

**Comment by syohex** [comment]
Sorry for late response. Its face is `popup-isearch-match`.

**Comment by wandersoncferreira** [comment]
Thanks!! Works great.
