### ISSUE TITLE
Add a option, when ac-menu is poped, auto enable ac-isearch

### ISSUE THREAD

**Issue by zw963** [auto-complete/auto-complete#478]
Thanks, I think this is a reasonable advance for AC.

**Comment by zw963** [comment]
As suggested by @m2ym.

```cl
(defun auto-complete-with-isearch ()
(interactive)
(auto-complete)
(ac-isearch))

(define-key ac-menu-map (kbd "TAB") 'auto-complete)
```

It seem like not worked in newest AC.

following is debug info:

```cl
Debugger entered--Lisp error: (wrong-type-argument commandp ac-complete-with-isearch)
  #<subr call-interactively>(ac-complete-with-isearch nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> ac-complete-with-isearch nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (ac-complete-with-isearch nil nil))
  call-interactively(ac-complete-with-isearch nil nil)
  command-execute(ac-complete-with-isearch)
```


And, even this worked, it still need a more ``TAB`` to trigger ``ac-isearch``, it same as a ``C-s``,
not enhanced more.

**Comment by zw963** [comment]
I think i explain the process I worked with AC is help a lot.

I don't like the default worked method,  TAB TAB ... RET, is some strang for me
to use, and in fact, it seem like not worked well with yasnippet.

I use AC worked process is:

1. Input a litter char
2.  If overladded complete(the first candidate) is what I want, I just expand it.
     it seem like worked with yasnippet too, if this cadidate is a snippet, it will be expanded.
3. if overladded complete is not what I want, after 0.8 second, I expect the `ac-menu` is 
poped, in this case, I expect I could C-n C-p to select a candidate (it worked), Or, input
some keyword in cadidates, just like isearch. But, current this worked only after I press
`C-s` after ac-menu is poped. this is anoised for me.


Followings is my config:

```el
;;;------------------------------auto-complete相关设置------------------------------
(require 'auto-complete-config)
(ac-config-default)
;; when close a emacs frame,  save ac history. (used with emacs daemon)
(add-hook 'delete-frame-functions (lambda (frame) (ac-comphist-save)))
(define-key ac-menu-map [(tab)] 'ac-complete)

(setq
 ac-dictionary-directories (expand-file-name "my-customized-settings/dict")
 ac-use-menu-map t                      ; popup 菜单使用 ac-menu-map,  如果希望使用 C-s, 必须开启此项.
 ac-auto-start 4                        ; 至少输入 4 个字符, 才启动 ac, 提高性能和与 yas 的兼容性.
 ac-use-quick-help nil                  ; 关闭 quick help
 ac-ignore-case nil                     ; 大小写总是敏感
 ac-dwim t                              ; TAB 将会直接展开一个 candidate? 即: 不是继续选择下一个?
 ;; ac-auto-show-menu nil                  ; 关闭自动显示 popup 菜单, 默认值 0.8 秒
 ;; ac-delay 0.5
 ;; ac-stop-words '("_" ",")
 ;; ac-expand-on-auto-complete nil
 )

(when (featurep 'enh-ruby-mode) (add-to-list 'ac-modes 'enh-ruby-mode))
(when (featurep 'inf-ruby-mode) (add-to-list 'ac-modes 'inf-ruby-mode))
```

**Comment by m2ym** [comment]
I am not actively working on OSS project recently, so let me just paste some workaround for your request:

```el
(defadvice ac-show-menu (before ac-isearch-after-show-menu activate)
  (when (popup-hidden-p ac-menu)
    (setq unread-command-events (append (listify-key-sequence (kbd "C-s")) unread-command-events))))
```

**Comment by zw963** [comment]
@m2ym , Cool, it worked!

 Thanks you very much!!

**Comment by zw963** [comment]
@m2ym, very sad to say, it seem like only worked in `emacs-lisp-mode`, when in `sh-mode` and `enh-ruby-mode`, the problem is described as following:

before ac-menu popup, we see the cursor is change to blue, and start blinking, we could see isearch
is start in minibuffer, which is blinking too. the buffer seem like into a dead loop, need `C-g` to exit
this status.

**Comment by zw963** [comment]
Seem like It just not work if only one candidates exist in any mode ...

**Comment by m2ym** [comment]
How about this one:

```el
(defadvice ac-show-menu (before ac-isearch-after-show-menu activate)
  (when (and (popup-hidden-p ac-menu) (not ac-show-menu))
    (setq unread-command-events (append (listify-key-sequence (kbd "C-s")) unread-command-events))))
```

**Comment by zw963** [comment]
@m2ym, work better, blinking is gone, though, only one candidate, still popup isearch in minibuffer, with no 
popup-menu poped or any overlay is displayed, it strange a little, I can change ``ac-auto-show-menu`` more longer, if only one candiate, I can just tab to select it before isearch is poped.

thank very much.

**Comment by zw963** [comment]
@m2ym, Thanks very much, this hack great improved AC use feeling until now. tough I use AC
from I use emacs several years ago, but AFAIU,  auto-complete for me, keep a status 
of can use, can ignore it,  even, it not convenience as `Meta-/`(hippie-expand) for me.

auto-isearch make me happy a lot for use AC, tough, it still a little need improved.
when only exist one candidate, could we not trigger ac-isearch? currently, ac-isearch
is still active, and we can see a blue cursor place there, and minibuffer like me search
kewords,  overlay complete tips is missing, I have to guess to input more search keyword,
to make ac menu is out.

Maybe you are busy for others things, But, if you could help, it would be very appreciated!

**Comment by zw963** [comment]
ping @m2ym ,  : )

**Comment by zw963** [comment]
@m2ym, I found ``(setq ac-candidate-menu-min 0)`` is seem like resolve this problem.

sorry for trouble, thanks.
