### ISSUE TITLE
Display problem with autocomplete in emacs (python)

### ISSUE THREAD

**Issue by iburunat** [auto-complete/auto-complete#499]
### Layout of autocomplete in python emacs not showing as it should
I recently installed in my Emacs (both Vanilla and Prelude) jedi, auto-complete, and yasnippet-snippets. However, when I press TAB for autocompletion, the display does not show "at point", but like this: https://snag.gy/X8cULh.jpg. I wonder how to get the more pleasing "box-at-point" display, that I see elsewhere.

**Comment by articuluxe** [comment]
You are using helm rather than auto-complete there. For the more pleasing display you desire, you will have to refrain from using a helm command and instead call auto-complete.

**Comment by iburunat** [comment]
Thanks. I disabled Helm mode, but I still don't get the proper display: https://snag.gy/jENLKn.jpg Additionally, I seem to get an error with Jedi, but I don't think my display problem is related (?).

**Comment by dickmao** [comment]
jedi.el is on life support.

**Comment by Gahamelas** [comment]
`pip install virtualenv` did the job.

**Comment by iburunat** [comment]
`pip install virtualenv` did the job!
