### ISSUE TITLE
Add page up/down commands

### ISSUE THREAD

**Issue by Lucretia** [auto-complete/auto-complete#501]
When auto-completing with a large set of tags, it would be useful to be able to page up and down through the list, with configurable key bindings.

**Comment by mpfeifer** [comment]
I don't know if this feature is currently available, but you can easily achive similar behavior if you do like this:

When the auto-completion starts the keymap ac-menu-map is in use. You could (defun) like this:

```
(defun my-easy-scroll-down () 
     (ac-next)
     (ac-next)
     (ac-next)
     (ac-next)
     (ac-next)
     (ac-next))
```
And bind this to some key:

`(define-key 'ac-menu-map (kbd "<down>") 'my-easy-scroll-down)`

**Comment by jcs090218** [comment]
This feature is definitely needed! Unfortunately I have not really got deep enough to the code yet. 

Anyway, PRs are welcome! :)

**Comment by piotrklibert** [comment]
@jcs090218 could you take a look at the PR :point_up:? I'm technically able to merge it, so it's fine if you don't have time, but I'd appreciate a review very much if you can find the time :)
