### ISSUE TITLE
Error running timer ‘ac-update-greedy’ / Error running timer ‘ac-show-menu’

### ISSUE THREAD

**Issue by Abuelodelanada** [auto-complete/auto-complete#508]
Hi,

I am migrating my emacs config to `use-package`, and I cannot find the way auto-complete works.

I have the following:

```elisp
(use-package ac-js2)
(use-package ac-php)
(use-package ac-php-core)
(use-package auto-complete
  :requires popup)

(ac-config-default)
(global-auto-complete-mode t)
```
But in the Messages buffer I get:

```log
Error running timer ‘ac-update-greedy’: (void-function ad-Advice-move-beginning-of-line)
Error running timer ‘ac-show-menu’: (void-function ad-Advice-move-beginning-of-line)
```

Am I missing something ?

**Comment by tarsius** [comment]
This package is looking for a new maintainer [while I am not the owner of this repository, I have never even used this package myself]. Despite that this package still has users but most of them are not hanging out here. You are more likely to find help in other places such as r/emacs.

**Comment by Abuelodelanada** [comment]
> This package is looking for a new maintainer [while I am not the owner of this repository, I have never even used this package myself]. Despite that this package still has users but most of them are not hanging out here. You are more likely to find help in other places such as r/emacs.

Thank you very much for your answer @tarsius !
