### ISSUE TITLE
Disable reviewer requirement?

### ISSUE THREAD

**Issue by jcs090218** [auto-complete/auto-complete#513]
I think I am the currently and only active maintainer? I think it would be easier to disable the needed reviewer feature for now until we have more active maintainers came in.

See link, [Enabling required reviews for pull requests](https://docs.github.com/en/enterprise/2.15/user/articles/enabling-required-reviews-for-pull-requests#:~:text=In%20the%20left%20menu%2C%20click,to%20require%20on%20the%20branch.).

@tarsius What do you think?

**Comment by tarsius** [comment]
Agreed. I've deleted that now.

**Comment by jcs090218** [comment]
Thank you!
