### ISSUE TITLE
Mind changing the organization's logo?

### ISSUE THREAD

**Issue by jcs090218** [auto-complete/auto-complete#514]
I wonder why the logo is a... car? 😕 

I am not an artist but I have Photoshop a small logo with some characters and information in it.

@tarsius What do you think?

![auto-complete](https://user-images.githubusercontent.com/8685505/96338065-24133000-10be-11eb-9bdd-4f3522db6aa7.png)

**Comment by tarsius** [comment]
> I wonder why the logo is a... car?

It's a Auto(mobil). I needed something that looks different from the logos of the other "groups" that I am a "member" of.

It's only intended as a temporary kludge and of course I would welcome a proper logo.

> I am not an artist but I have Photoshop a small logo with some characters and information in it.

If you drop the url then that might work, at least as a temporary solution.

**Comment by jcs090218** [comment]
> If you drop the url then that might work, at least as (yet another) temporary solution.

You mean remove the url from the logo?

![auto-complete](https://user-images.githubusercontent.com/8685505/96349579-17550300-10e3-11eb-96f5-b788daa572ba.png)

**Comment by tarsius** [comment]
Turns out even the "big" text is unreadable when shrunk enough.

**Comment by jcs090218** [comment]
Yeah, this kind a suck. I am thinking maybe changing the word to something else? Maybe just `ac`; stands for autocomplete?

**Comment by jcs090218** [comment]
I will just close this issue for now. This is just a temporary logo; and the new logo shall opens in the next new post! Thanks!

**Comment by jcs090218** [comment]
Okay, I have problem with the old logo. I am not able to see the image very well on my phone.

@tarsius How about this one?

![logo](https://user-images.githubusercontent.com/8685505/111336137-ed166a00-86af-11eb-8e35-0d7436a52801.png)

**Comment by tarsius** [comment]
Done.
