### ISSUE TITLE
ac-quick-help is not working on manual invocation

### ISSUE THREAD

**Issue by vspinu** [auto-complete/auto-complete#67]
Hi again,

I have 

```
 (define-key ac-completing-map (kbd "M-h") 'ac-quick-help t)
```

but  each invocation of M-h doesn't do anything, no quick-help whatsoever. 

If I set ac-use-quick-help  to t, quick-help shows properly.

Any ideas?

here is my setup:

```
(setq ac-auto-show-menu 0.5
      ac-candidate-limit 100
      ac-delay 0.2
      ac-disable-faces (quote (font-lock-comment-face font-lock-doc-face))
      ;; ac-ignore-case 'smart
      ac-menu-height 12
      ac-quick-help-delay 1.0
      ac-quick-help-prefer-pos-tip t
      ;; ac-use-menu-map nil
      ;; ac-use-overriding-local-map nil
      ac-use-quick-help nil)
```

Thanks.

**Comment by LaDilettante** [comment]
I'm still running into this of quick help cannot be manually invoked.

What should I have in my `.emacs`? If I used what's provided by OP, i.e.

`(define-key ac-completing-map (kbd "M-h") 'ac-quick-help t)`

emacs complains that there are too many arguments.

If I use

`(define-key ac-completing-map (kbd "M-h") 'ac-quick-help)`

then `M-h` is not rebound.
